encoding: utf-8
title: "cryptax.github.io"
description: "Cryptax's hand bag :)"
theme: jekyll-theme-hacker
avatar: https://github.com/cryptax/cryptax.github.io/raw/master/images/ghost.png

exclude: 
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
