baseURL = 'https://cryptax.github.io/'
defaultContentLanguage = "en"
languageCode = ['en-us','fr']
hasCJKLanguage = false
title = 'The handbag of Cryptax'
theme = 'LoveIt'
paginate = 10
enableEmoji = true

[author]
name = "Cryptax"
email = "crypto.maniak@gmail.com"

[menu]
  [[menu.main]]
  weight = 1
  identifier = "posts"
  name = "Write-ups"
  url = "/posts/"
  # title is shown when you over on the menu link
  title = "CTF write-ups"
  
  [[menu.main]]
  weight = 2
  identifier = "talks"
  name = "Publications"
  url = "/talks/"
  title = "Workshop, papers, talks"
  
  [[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

  [[menu.main]]
  weight = 4
  identifier = "about"
  name = "About"
  url = "/about/"
  title = "About me"

[params]
# site default theme ["auto", "light", "dark"]
defaultTheme = "auto"
dateFormat = "2006-01-02"
[params.header]
  [params.header.title]
  name = "The handbag of Cryptax"

  [params.footer]
  enable = true
  # show Hugo and theme info
  hugo = true
  # show copyright info
  copyright = true
  author = true
  since = 2023

  [params.section]
  paginate = 20

  [params.search]
  enable = true
  # search engine: ["lunr", "algolia"]
  type = "lunr"
  contentLength = 4000
  maxResultLength = 10
  snipperLength = 30

  [params.home]
    [params.home.profile]
    enable = true
    avatarURL = "images/ghost.png"
    title = "Cryptax"
    subtitle = "CTF write-ups, mobile malware, IoT, crypto..."
    # whether to use typeit animation for subtitle
    typeit = true
    social = true
    disclaimer = "This website is personal and does not represent my employer"

    [params.home.posts]
    enable = true
    paginate = 3

  [params.social]
  Twitter = "@cryptax"
  GitHub = "cryptax"
  Linkedin = "axelle-apvrille-7b99154"
  Medium = "@cryptax"
  Youtubechannel = "UCS3TXgeU6tUAVvprYRjnqMg"
  Discord = "cryptax#1854"

    [params.social.Mastodon]
    weight = 1
    id = "@cryptax"
    prefix = "https://mastodon.social"
    title = "Mastodon"

  [params.toc]
  enable = true
  auto = true

  [params.page]
  lightgallery = false
  fontawesome = true
  linkToMarkdown = true
    [params.page.code]
    # whether to show the copy button of the code block
    copy = true
    maxShownLines = 50

  [params.typeit]
  speed = 100
  cursorSpeed = 1000
  cursorChar = "|"
  duration = -1

  [params.analytics]
  enable = false

  [params.cookieconsent]
  enable = false

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":filename"

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
